version: '3.3'

services:
   esb-services:
     container_name: esb-services
     build: 
       context: ./ESB_NodeJs
     ports:       
       - 3000:3000 
     restart: always
     volumes:
       - type: bind
         source: ./ESB_NodeJs
         target: /usr/src/app
